%YAML 1.2
---
name: "Maia-2200"
gpu: 0

dataset:
  input_train: 'C:\Users\vieta\Desktop\Maia Chess\Training\training data\*'
  input_test: 'C:\Users\vieta\Desktop\Maia Chess\Training\validation\*'
  train_workers: 12
  test_workers: 4
  

training:
    precision: 'single'
    batch_size: 1024
    num_batch_splits: 1
    test_steps: 1000
    train_avg_report_steps: 100
    total_steps: 400000
    checkpoint_steps: 10000
    shuffle_size: 250000
    lr_values:
        - 0.2
        - 0.02
        - 0.002
        - 0.0002
    lr_boundaries:
        - 80000
        - 200000
        - 360000
    policy_loss_weight: 1.0
    value_loss_weight: 1.0

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
...
